### ISSUE TITLE
Web interface: "Home" navigation button disappears in wide window

### ISSUE THREAD

**Issue by gtim** [Drithyl/MrClockwork-v4#59]
Thank you for a fantastic hosting bot and web interface!

I noticed that the top-bar covers the "Home" button when the window is wide on Chrome 96.0.4664.45, Windows 10.

![image](https://user-images.githubusercontent.com/1546926/144750935-0a6b9005-b65d-4b7f-8e9b-20ca3e5f2c12.png)

**Comment by lolbat** [comment]
I will be looking into that tomorrow. Thanks for posting it

**Comment by lolbat** [comment]
I've posted a pull request with a fix for this
