### ISSUE TITLE
No label on turn reminders

### ISSUE THREAD

**Issue by Drithyl** [Drithyl/MrClockwork-v4#60]
@lolbat 
![Capture](https://user-images.githubusercontent.com/28873180/144759744-2138310e-0b95-4ee1-af6e-83f5645fa5ea.PNG)

The dropdown for turn reminders could use a label. The numbers are meant to be hour markers for when the bot sends a DM reminder to the player that they have not played their turn. For example, 12 would be when 12h are left. Not sure what a clear label would be. "Turn reminder when hours left"?

**Comment by lolbat** [comment]
Should the dropdown be disabled unless they select "Receive timer reminders even when the turn is marked as finished?"?

I know it is enabled by default but if they deselect the checkbox should the dropdown then be disabled?

Perhaps "Post reminder when how many hours are left?" as a label?

**Comment by lolbat** [comment]
<img width="833" alt="Screen Shot 2021-12-07 at 9 58 42 AM" src="https://user-images.githubusercontent.com/4564571/145072825-e4bd3447-d8d8-441b-a42e-594a2f47ec74.png">

**Comment by Drithyl** [comment]
> Should the dropdown be disabled unless they select "Receive timer reminders even when the turn is marked as finished?"?
> 
> I know it is enabled by default but if they deselect the checkbox should the dropdown then be disabled?
> 
> Perhaps "Post reminder when how many hours are left?" as a label?

Yeah, it would be ideal if the dropdown disappeared if that checkbox is not selected. For the label I would tweak the one you made and say "Send reminder..." instead of "Post".

**Comment by lolbat** [comment]
'Send' it is
