### ISSUE TITLE
No way to stop reminders

### ISSUE THREAD

**Issue by ejones44** [Drithyl/MrClockwork-v4#91]
If you go to game preferences and setup a turn reminder, there is no way to remove it later.  Removing your selections and hitting "save preferences" doesn't update your preference to have no reminder.

![image](https://user-images.githubusercontent.com/11811765/167430051-06a2481a-77c6-4c8d-939b-32991444aad8.png)

![image](https://user-images.githubusercontent.com/11811765/167430100-bad5e5c1-978d-4477-9c03-8b0ddfc8b827.png)

**Comment by Drithyl** [comment]
Hopefully should have been resolved in my latest commit.
