### ISSUE TITLE
"Online" and "Offline" statuses on the list of servers look too similar

### ISSUE THREAD

**Issue by Drithyl** [Drithyl/MrClockwork-v4#94]
Ideally, a colour-coding could be added to the table where the status of servers is displayed, to make it much faster at a glance and make it easy on the eye to see which servers might have issues. This could also apply to the user list of games they're playing, as those can also sometimes be offline, either by the game being down or the server that the game is hosted on being offline.

![image](https://user-images.githubusercontent.com/28873180/170363663-15abd802-dee0-417b-8b43-05599201f728.png)

**Comment by Edwardscb** [comment]
Made an edit which should turn an online server bold with green as the font color. Pull request pending.

**Comment by Drithyl** [comment]
Appreciate it; merged the pull request.
